### PR TITLE
Feat/41 contributors page gong

### PR DESCRIPTION
**Pull request by QuangLyHo**
-Created new contributors.html
-Added a navigation bar to header
-Added a util.js page for code to close the toggler when screen is larger than breakpoint, so hamburger menu doesn't remain open

I designed the nav bar mobile view to column style, let me know if you guys prefer it to stay row style instead.

### CODE REVIEW

**Comment by terrifricker** [comment]
I think I like the nav as a row in mobile because it takes less space.

**Review by alekzandriia — APPROVED** [review]
Love it!! Works well. 😊 

When we change the title, maybe we can update the style so that the header overlaps the page content instead of pushing it down? `position: fixed; z-index: 10;`

**Comment by QuangLyHo** [comment]
> Love it!! Works well. 😊 
> 
> 
> 
> When we change the title, maybe we can update the style so that the header overlaps the page content instead of pushing it down? `position: fixed; z-index: 100;`

Definitely, when I get a chance I'll update to reflect that.

Whats your thoughts on the hamburger?
Terri votes for row style, do you have any objections?

**Comment by terrifricker** [comment]
I have a couple of questions.

First, can the javascript just go in the one javascript file instead of making a new file?
Second, I know this is your second pull request for this, but I still think the member page should just be hidden and unhidden with javascript class changes.  (I guess we need @alekzandriia to weigh in, since Yasmin requested it.)

And actually, I think in our Figma, we don't have the header on the front page and it doesn't have the title - but I don't remember what we talked about at our last meeting.  I didn't take notes on the header because I wasn't working on it.

Should we confirm were we want it and what should be in it before we add it?

(And I hate that I have questions for each of your sections, gong.  But this is what I was worried about at the meeting.  I think we wanted some ideas from Alexandria (like she did for the category page, and is working on for the landing page) before you and I had more work so we wouldn't end up with conflicts.)

**Comment by alekzandriia** [comment]
> > Love it!! Works well. 😊
> > When we change the title, maybe we can update the style so that the header overlaps the page content instead of pushing it down? `position: fixed; z-index: 100;`
> 
> Definitely, when I get a chance I'll update to reflect that.
> 
> Whats your thoughts on the hamburger? Terri votes for row style, do you have any objections?

Hmm, I think I also like the idea of having the hamburger in the top right (row). That's just how I see most apps/sites formatted.

**Comment by QuangLyHo** [comment]
There is code in the index.js that causes problems in the contributors.html because it calls on elements that don't exist in contributors.html.

Is this a huge problem to have a separate JS page? 

The index.js would need to be re-written for it all to be on one page. Which isn't a huge problem, but at the same time I don't see why having a separate JavaScript page that runs a specific block for both pages is an issue.

Let me know your thoughts and we can figure it out together

**Comment by terrifricker** [comment]
> There is code in the index.js that causes problems in the contributors.html because it calls on elements that don't exist in contributors.html.
> 
> Is this a huge problem to have a separate JS page?

Not at all.  I just didn't understand it.  Actually it makes sense to me now because it is a separate page.  Of course that would be a problem.

**Comment by terrifricker** [comment]
Ready for me to pull it? @QuangLyHo

**Pull request merged**
