### PR TITLE
Feat/18 Main Category Screen

### LINKED ISSUE #18: Create screen that shows main categories

### PR DESCRIPTION
**Pull request by terrifricker**

### CODE REVIEW

**Review by alekzandriia — APPROVED** [review]

**Review by alekzandriia — CHANGES_REQUESTED** [review]
Are we creating a separate page for the categories or should we add this to the _index.html_? & then each "page" will be a `main` that’s `.hidden` when not being displayed. That way we’d also just have one _index.css_ for all our styling.

We could also change some `div`s -> `section`s to be more semantic.

For responsiveness, it might be good to add `flex-wrap:wrap` to the container and a `min-width:450px` to the left/right sections so the content adapts to smaller screens.

& idk if the image should be positioned absolutely... Maybe you can add it to the left section as a background image? Like `background: url('images/chuck-norris-kick.png') center center no-repeat;`. What do you think?

**Comment by terrifricker** [comment]
I think we can have just one index.html.  I wasn't sure about putting it there right away.  I will change some divs to sections.  I hadn't thought about making such quick change for responsiveness!

Background image is a great idea, too.  The resolution on this image isn't good.  I'm going to look for a better one, too.

**Comment by terrifricker** [comment]
The background-image positioning wasn't were I wanted, so I left it as is with absolute positioning.
I just made the outside div a \<section>.
I added the flex-wrap and min-width and it moves to a single column now when I decrease the screen size.

**Review by Emimint — APPROVED** [review]

**Review by QuangLyHo — CHANGES_REQUESTED** [review]
I was thinking what @alekzandriia was saying as well, single page and categories being on the front page? Lemme know what you think

**Comment by terrifricker** [comment]
@alekzandriia and @QuangLyHo I thought for this sprint, we would leave the first page exactly like the canva template.  @Emimint has a pull request for that page.  I didn't want to add to index.html until she had created her page, so I created another html file (temporary) to hold my code as well as an extra css file to hold my css.

I also have html and css for the sub-category screen ready to go, but still just in my local repository.  I was thinking that at least having the code in the repository would make it available for Alexandria to use right now, instead of waiting for all the pull requests to catch up.  The code blocks can be moved around wherever we want them to end up.

In its current form, this pull request can be merged without conflicting with Emilie's pull request.

**Comment by terrifricker** [comment]
Closing. I will keep on my local repository, then add to index.html when appropriate.

**Pull request closed without merging**
