### PR TITLE
added back button to facts page

### PR DESCRIPTION
**Pull request by QuangLyHo**
added a back button that leads back to categories

### CODE REVIEW

**Comment by terrifricker** [comment]
I haven't figured out how to make a video of it, but sometimes when hovering on the image, it wobbles back and forth really fast.  I think because as I hover, the image underneath moves from out from under the hover.

@alekzandriia can we decide to maybe not have it flip on hover and just have the photo already flipped the other direction and say "Back" like a mirror image and just have it animate exactly like the "Next" button?

**Comment by QuangLyHo** [comment]
> I haven't figured out how to make a video of it, but sometimes when hovering on the image, it wobbles back and forth really fast. I think because as I hover, the image underneath moves from out from under the hover.
> 
> @alekzandriia can we decide to maybe not have it flip on hover and just have the photo already flipped the other direction and say "Back" like a mirror image and just have it animate exactly like the "Next" button?

Yea, I see what you mean with the hovering jitter, I can't seem to fix the jittering so i went ahead and just did a no hover effect, and instead it just rotates on load.

Also, it is not fair to just put it all on Alekzandriia to decide theres also Yasmin, Prisca, and David to consider, not that it's a super big deal but they are apart of the team too. I'll get a video of the no hover effect in the discord and you can have a look there and see what you think.

**Comment by alekzandriia** [comment]
If we do want to do the hover effect then we could maybe do something like this? 

I know Yasmin really wants some kind of cool animation so it would be nice to deliver on her vision  :) 

I was having issues animating the image as a CSS `background` property so I used an `img` tag instead & used vmin as responsive size units so everything scales with the page.

**index.html**
```
<section class="back-area" id="back">
        <img src="images/chuck-norris-kick.png" alt="" class="back-img" />
</section>
```
**style.css**
```
.back-area {
  width: 20vmin;
  position: absolute;
  bottom: 0;
  left: 0;
  margin: 2rem;
  cursor: pointer;
}
.back-img {
  transform: scaleX(-1);
}

.back-img:hover {
  transition: rotate 400ms ease-in-out;
  rotate: 360deg;
}
.back-area:hover::before {
  content: "Back";
  font-size: 4vmin;
  position: relative;
  bottom: -14vmin;
  left: 0;
}
```
Which results in this effect:

https://user-images.githubusercontent.com/5445437/215668443-c9a0da44-3f50-47f9-bd4a-c5f8cb75f848.mov

**Comment by QuangLyHo** [comment]
I like it, checks all the boxes. smooth functions and checks all boxes

**Comment by QuangLyHo** [comment]
I like it, smooth, functional, and adds animation. Checks all boxes :)

**Comment by terrifricker** [comment]
> Also, it is not fair to just put it all on Alekzandriia to decide theres also Yasmin, Prisca, and David to consider, not that it's a super big deal but they are apart of the team too. I'll get a video of the no hover effect in the discord and you can have a look there and see what you think.

Thank you, Gong.  You are right.  I needed to hear this.

**Review by terrifricker — APPROVED** [review]
Giving approval so you can merge as soon as it is ready.

**Comment by QuangLyHo** [comment]
> > Also, it is not fair to just put it all on Alekzandriia to decide theres also Yasmin, Prisca, and David to consider, not that it's a super big deal but they are apart of the team too. I'll get a video of the no hover effect in the discord and you can have a look there and see what you think.
> 
> 
> 
> Thank you, Gong.  You are right.  I needed to hear this.
> 
> 
> 
> 

All good. All part of the learning process for working collaboratively.

**Comment by QuangLyHo** [comment]
> Giving approval so you can merge as soon as it is ready.

And I was gonna actually suggest is @alekzandriia wanted to make a new PR. I realized too late that I was working on a previous feature branch and didn't update the branch to reflect the feature being worked on

**Comment by alekzandriia** [comment]
> > Giving approval so you can merge as soon as it is ready.
> 
> And I was gonna actually suggest is @alekzandriia wanted to make a new PR. I realized too late that I was working on a previous feature branch and didn't update the branch to reflect the feature being worked on

Okay, I made a PR. 👍😊 Copied the animation style over to the next button as well so that they match. Think that prob looks better?

**Pull request closed without merging**
